const userData = [
    {
        id:"1",
        name:"Abdunazarov",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"2",
        name:"Abdurashidov",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"3",
        name:"Alimov B",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"4",
        name:"Amirov Sh",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"5",
        name:"Asadov A",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"6",
        name:"Bafoyev I",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"7",
        name:"Baxtiyorov",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"8",
        name:"Egamberdiyev",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"9",
        name:"Ergashev",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"10",
        name:"Ergashev Sh",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"11",
        name:"Ergashev S",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
    },
    {
        id:"12",
        name:"Eshonqulov S",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"13",
        name:"Ismatilloyev G'",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"14",
        name:"Jurabayev X",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"15",
        name:"Meliyev H",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"16",
        name:"Misirov E",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"17",
        name:"Musayev M",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"18",
        name:"Muzaffarov B",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"19",
        name:"Narzullayev A",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"20",
        name:"Nasretdinov Sh",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"21",
        name:"Norqobilov M",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"22",
        name:"Nuraliyev Sh",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"23",
        name:"O'roqov S",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"24",
        name:"O'roqov T",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"25",
        name:"Qahramonov F",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"26",
        name:"Sahripov D",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"27",
        name:"Toshbotirov O",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"28",
        name:"Tursunov O",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"29",
        name:"Uzoqov B",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"30",
        name:"Uzoqov N",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"31",
        name:"Xaitov A",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"32",
        name:"Xudoynazarov X",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"33",
        name:"Yo'ldoshev Y",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      },
      {
        id:"34",
        name:"Yoshiuzoqov O",
        semestr1:"",
        semestr2:"",
        yakuniyBall:"",
        semestr3:"",
        semestr4:"",
        yakuniyBall2:""
      }
];

export default userData;