const userData = [
    {
        id:"1",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"2",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"3",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"4",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"5",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"6",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"7",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"8",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"9",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"10",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"11",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"12",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"13",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"14",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"15",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"16",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"17",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"18",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"19",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    },
    {
        id:"20",
        sana:"",
        kamchiliklar:"",
        muddati:"",
        ism:""
    }
];

export default userData;